export const EDU_API_BASE = 'http://api.ikonakademi.com/';
export const EDU_API_LOGIN = EDU_API_BASE+'api/Token';
export const EDU_API_LOGIN_FIRST_STEP = EDU_API_BASE + 'User/LoginStep1'
export const EDU_API_COURSES = EDU_API_BASE+"course/Topic"
export const EDU_API_CONTROL_EMAIL = EDU_API_BASE + 'User/EmailCheck'
export const EDU_API_GET_CART_LIST = EDU_API_BASE+'course/Topics'
export const EDU_API_CREATE_USER = EDU_API_BASE  + 'User'
export const EDU_API_CREATE_USER_PHONE_VERIFY = EDU_API_BASE + 'User/SendActivationCode'
export const EDU_API_COURSE_BASE = EDU_API_BASE+'course'
export const EDU_API_SOCIAL_LOGIN =EDU_API_BASE + 'User/SocialLogin';
export const EDU_API_GET_COURSE_INFO =EDU_API_BASE + 'course/Video';
export const EDU_API_GET_BASKET_ID = EDU_API_BASE+'basket';
export const EDU_API_GET_CREDIT_CARD = EDU_API_BASE + 'Payment'
export const EDU_API_GET_ORDERED_COURSES = EDU_API_BASE+'basket/UserOrder'
export const EDU_API_ADRESS_CITY= EDU_API_BASE + 'Adress/Cities'
export const EDU_API_ADRESS_DISTRICT = EDU_API_BASE + 'Adress/Distritcs/'
export const EDU_API_ADRESS_NEIGHBOORS = EDU_API_BASE + 'Adress/Neighboors/'
export const EDU_API_ADRESS_LOCALITY = EDU_API_BASE + 'Adress/Localities/'
export const EDU_API_PAYMENT_BYCREDITCARD = EDU_API_BASE + 'Payment'

export const EDU_API_GET_USER_INFO = EDU_API_BASE + 'User'
export const EDU_API_UPDATE_USER_INFO = EDU_API_BASE + 'User/Update'
export const EDU_APO_ORDER_STATUS = EDU_API_BASE + 'basket'
